name: tu_cancha
description: Una app para registrar los agendamientos de tres canchas

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  provider: ^6.0.5
  path_provider: ^2.0.14
  intl: ^0.18.0
  flutter_easyloading: ^3.0.5
  dio: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.3


flutter:
  uses-material-design: true

  assets:
      - assets/icons/court.png
